name: CI (build JAR)
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'   # matches your pom.xml
      - name: Build
        run: mvn -B -q -DskipTests package
      - name: Upload JAR (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
